version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "deps(actions): "
    open-pull-requests-limit: 20
    schedule:
      interval: "cron"
      cronjob: "19 05 * * *"
    rebase-strategy: disabled
    cooldown:
      default-days: 3
      exclude:
        - "quotidian-ennui/*"
    groups:
      workflows-olio:
        patterns:
          - "quotidian-ennui/workflows-olio/*"
          - "quotidian-ennui/actions-olio/*"
