name: Update documentation

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, edited]

defaults:
  run:
    shell: bash

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PR_GITHUB_USER: qe-repo-updater[bot] <152897211+qe-repo-updater[bot]@users.noreply.github.com>

jobs:
  autodoc:
    name: autodoc
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    steps:
      - name: Get Token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ vars.WORKFLOW_UPDATE_CLIENT_ID }}
          private-key: ${{ secrets.WORKFLOW_UPDATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "${{ github.event.repository.name}}"
          permission-contents: write

      - name: Install auto-doc
        uses: jaxxstorm/action-install-gh-release@25e24d2d23ae098373794ef1d6faecb48ee52da8 # v3.0.0
        with:
          repo: tj-actions/auto-doc

      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false

      - name: Run auto-doc
        env:
          ACTION_FILE: action.yml
          README_FILE: README.md
        run: |
          #!/usr/bin/env bash

          echo "::group::auto-doc generator"
          echo "Generating documentation for $base"
          auto-doc --colMaxWords 100 --filename "$ACTION_FILE" --output "$README_FILE"
          echo "::endgroup::"

      - name: Commit changes
        uses: iarekylew00t/verified-bot-commit@5b4e8852dc472093935b8debcb81459bb79f7986 # v2.3.2
        with:
          if-no-commit: info
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ steps.app-token.outputs.token }}
          message: "docs: update action documentation"
          update-local: false
          files: |
            **/*.md
