name: dependabot-merge
run-name: Merge dependabot-pr (${{ github.event.client_payload.detail.pull_request }})
on:
  repository_dispatch:
    types:
      - dependabot-merge

permissions: {}

# A push via dependabot basically means that the github actions
# have been upgraded;
jobs:
  actions_merge:
    uses: quotidian-ennui/workflows-olio/.github/workflows/action-dependabot-merge.yml@6099af4157e6653a07431f39552a6b36bb331d2b # v2.1.0
    with:
      client_id: ${{ vars.WORKFLOW_UPDATE_CLIENT_ID }}
    secrets:
      app_private_key: ${{ secrets.WORKFLOW_UPDATE_KEY }}
