name: dependabot-merge
run-name: Dependabot workflow changes (${{ github.event.client_payload.detail.pull_request }})
on:
  repository_dispatch:
    types:
      - dependabot-merge

permissions: {}

jobs:
  actions_merge:
    uses: quotidian-ennui/workflows-olio/.github/workflows/action-dependabot-merge.yml@290daed67f03ed2f2502eee057f35e61327b1bef # v1.0.0
    secrets: inherit
