name: release
on:
  push:
    tags:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  create-release:
    uses: quotidian-ennui/workflows-olio/.github/workflows/create-release.yml@290daed67f03ed2f2502eee057f35e61327b1bef # v1.0.0
    secrets: inherit
    permissions:
      contents: write
