name: release
on:
  push:
    tags:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  create-release:
    uses: quotidian-ennui/workflows-olio/.github/workflows/create-release.yml@da5bf91c178d83ccfc784f0db2b4c0d62180ca77 # v2.2.6
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
