name: release
on:
  push:
    tags:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  create-release:
    uses: quotidian-ennui/workflows-olio/.github/workflows/create-release.yml@4beb72c77ee9fb289c0bb9a5eb8d61256bb9935a # v2.0.0
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
